import { PublicHeader } from "@/components/PublicHeader";
import { Card } from "@/components/ui/card";
import { AlertCircle, Github, Code, CheckCircle, XCircle } from "lucide-react";

export default function Rules() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900">
      <PublicHeader />
      
      <div className="container py-20">
        <div className="max-w-4xl mx-auto">
          {/* Header */}
          <div className="text-center mb-12">
            <h1 className="text-5xl md:text-6xl font-bold text-white mb-4">
              Competition <span className="bg-gradient-to-r from-red-500 via-yellow-500 to-green-500 bg-clip-text text-transparent">Rules</span>
            </h1>
            <p className="text-xl text-white/80">
              Fair play guidelines for HackGreenwich 2026
            </p>
          </div>

          {/* Important Notice */}
          <Card className="mb-8 p-6 bg-red-500/10 border-red-500/30 backdrop-blur-sm">
            <div className="flex items-start gap-4">
              <AlertCircle className="h-6 w-6 text-red-400 flex-shrink-0 mt-1" />
              <div>
                <h3 className="text-xl font-bold text-red-400 mb-2">Important: Event Dates & Times</h3>
                <p className="text-white/90">
                  HackGreenwich 2026 runs from <strong>March 1st, 2026 at 12:00pm EST</strong> to <strong>March 3rd, 2026 at 12:00pm EST</strong>. All projects must be started after the official start time. Any work done before this will result in disqualification.
                </p>
              </div>
            </div>
          </Card>

          {/* Vibe Coding Rule */}
          <Card className="mb-8 p-8 bg-white/5 backdrop-blur-sm border-white/10">
            <div className="flex items-start gap-4 mb-6">
              <Code className="h-8 w-8 text-yellow-400 flex-shrink-0" />
              <div>
                <h2 className="text-3xl font-bold text-white mb-3">The 75% Rule: Vibe Coding Limits</h2>
                <p className="text-white/80 text-lg leading-relaxed">
                  Projects must be <strong>at least 25% manually coded</strong>. This means a maximum of 75% of your project can be "vibe coded" (generated by AI tools like Cursor, GitHub Copilot, ChatGPT, Claude, etc.).
                </p>
              </div>
            </div>

            <div className="space-y-4 ml-12">
              <div className="flex items-start gap-3">
                <CheckCircle className="h-5 w-5 text-green-400 flex-shrink-0 mt-1" />
                <p className="text-white/70">
                  <strong className="text-white">Allowed:</strong> Using AI for boilerplate, debugging, documentation, and learning new concepts
                </p>
              </div>
              <div className="flex items-start gap-3">
                <CheckCircle className="h-5 w-5 text-green-400 flex-shrink-0 mt-1" />
                <p className="text-white/70">
                  <strong className="text-white">Allowed:</strong> AI-assisted code completion and suggestions while you write
                </p>
              </div>
              <div className="flex items-start gap-3">
                <XCircle className="h-5 w-5 text-red-400 flex-shrink-0 mt-1" />
                <p className="text-white/70">
                  <strong className="text-white">Not Allowed:</strong> Generating entire features or components without understanding or modification
                </p>
              </div>
              <div className="flex items-start gap-3">
                <XCircle className="h-5 w-5 text-red-400 flex-shrink-0 mt-1" />
                <p className="text-white/70">
                  <strong className="text-white">Not Allowed:</strong> Copy-pasting large blocks of AI-generated code without customization
                </p>
              </div>
            </div>

            <div className="mt-6 p-4 bg-yellow-500/10 border border-yellow-500/30 rounded-lg">
              <p className="text-white/90">
                <strong className="text-yellow-400">How we verify:</strong> Judges will review your code structure, commit history, and ask questions about implementation details during demos. Be prepared to explain your design decisions and how your code works.
              </p>
            </div>
          </Card>

          {/* GitHub Requirements */}
          <Card className="mb-8 p-8 bg-white/5 backdrop-blur-sm border-white/10">
            <div className="flex items-start gap-4 mb-6">
              <Github className="h-8 w-8 text-purple-400 flex-shrink-0" />
              <div>
                <h2 className="text-3xl font-bold text-white mb-3">GitHub Commit Requirements</h2>
                <p className="text-white/80 text-lg leading-relaxed">
                  You must maintain a <strong>public GitHub repository</strong> with regular commits throughout the hackathon to prove your project was built during the event.
                </p>
              </div>
            </div>

            <div className="space-y-6 ml-12">
              <div>
                <h3 className="text-xl font-semibold text-white mb-3">Required Evidence:</h3>
                <ul className="space-y-2 text-white/70">
                  <li className="flex items-start gap-2">
                    <span className="text-green-400 mt-1">•</span>
                    <span><strong className="text-white">First commit:</strong> Must be timestamped after March 1st, 2026, 12:00pm EST</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-green-400 mt-1">•</span>
                    <span><strong className="text-white">Regular commits:</strong> Show consistent progress throughout the hackathon period (March 1-3)</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-green-400 mt-1">•</span>
                    <span><strong className="text-white">Meaningful messages:</strong> Commit messages should describe what was added/changed</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-green-400 mt-1">•</span>
                    <span><strong className="text-white">Public repository:</strong> Must be accessible for judges to review commit history</span>
                  </li>
                </ul>
              </div>

              <div className="p-4 bg-blue-500/10 border border-blue-500/30 rounded-lg">
                <p className="text-white/90">
                  <strong className="text-blue-400">Pro tip:</strong> Commit early and often! Not only does this prove your timeline, but it also protects your work and makes collaboration easier. Aim for commits every 30-60 minutes as you complete features or fix bugs.
                </p>
              </div>
            </div>
          </Card>

          {/* Additional Rules */}
          <Card className="p-8 bg-white/5 backdrop-blur-sm border-white/10">
            <h2 className="text-3xl font-bold text-white mb-6">Additional Guidelines</h2>
            
            <div className="space-y-4 text-white/70">
              <div>
                <h3 className="text-lg font-semibold text-white mb-2">Team Size</h3>
                <p>Teams can have 1-4 members. Solo participants are welcome!</p>
              </div>

              <div>
                <h3 className="text-lg font-semibold text-white mb-2">Intellectual Property</h3>
                <p>You retain all rights to your project. By participating, you grant HackGreenwich permission to showcase your project in promotional materials.</p>
              </div>

              <div>
                <h3 className="text-lg font-semibold text-white mb-2">Code of Conduct</h3>
                <p>Be respectful, inclusive, and supportive of all participants. Harassment, discrimination, or unsportsmanlike conduct will result in immediate disqualification.</p>
              </div>

              <div>
                <h3 className="text-lg font-semibold text-white mb-2">External Resources</h3>
                <p>You may use open-source libraries, frameworks, and APIs. Pre-existing code from your own projects is allowed if properly disclosed and documented in your README.</p>
              </div>

              <div>
                <h3 className="text-lg font-semibold text-white mb-2">Judging Criteria</h3>
                <p>Projects will be evaluated on innovation, technical execution, design/UX, and presentation. Judges' decisions are final.</p>
              </div>
            </div>
          </Card>

          {/* Footer CTA */}
          <div className="mt-12 text-center">
            <p className="text-white/60 mb-4">
              Questions about the rules? Reach out to the organizers on our Discord server.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
